### PR TITLE
Add PL shortcut

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by chaica** [comment]
Do you use it or it's just to provide potential syntactic sugar? I'm not feeling like using it myself. So if you use it yourself I'll merge. Otherwise I think it's not needed.

**Comment by fgallaire** [comment]
@chaica The question is not only you and me !! But all the (potential) users of persistentlist. It's a syntactic sugar at no cost !

**Comment by chaica** [comment]
Yes it is. No dead code. if nobody uses it and nobody claimed it, it's a unneeded cost to maintain on long term.

**Comment by fgallaire** [comment]
It's a logical problem, if it's not here nobody can use it !!
It's ZERO cost to maintain.

**Comment by chaica** [comment]
sorry but I don't agree here. No use for a feature not required by a specific user or someone telling it's painful to use it as it is now. I won't add code that someone some day may use... or not. And it's not a logicial issue, people needing someone knows how to claim it or to make a feature request.

**Comment by fgallaire** [comment]
1) Yes, it's painful to use as it is now, it's said !
2) If it's painful to use, you don't have claims, you just don't have users !

**Comment by chaica** [comment]
I'll wait some more claims before adding it. Seems not needed to me. And thanks for your contribution :)

**Pull request closed without merging**
